apiVersion: batch/v1
kind: Job
metadata:
  name: unifrac-nrp-300k-8
spec:
  completions: 2
  parallelism: 2
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
              - key: env
                operator: In
                values:
                - nrp
      tolerations:
      - effect: NoSchedule
        key:  nautilus.io/nrp-testing
        operator: Exists
      containers:
      - name: test
        image: sfiligoi/unifrac
        command:
        - "/bin/bash"
        args:
        - "-l"
        - "-c"
        - "source /root/run_300k_8.sh"
        env:
        - name: POD_NAME_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 512Gi
            cpu: 64
            nvidia.com/gpu: 8
            ephemeral-storage: 320Gi
          requests:
            memory: 300Gi
            cpu: 30
            nvidia.com/gpu: 8
            ephemeral-storage: 30Gi
        volumeMounts:
        - name: unifrac-nrp-script
          mountPath: /root/run_300k_8.sh
          subPath: run_300k_8.sh
        - name: unifrac-nrp-script2
          mountPath: /root/run_300k_support.sh
          subPath: run_300k_support.sh
      restartPolicy: Never
      volumes:
      - name: unifrac-nrp-script
        configMap:
          items:
          - key: run_300k_8.sh
            path: run_300k_8.sh
          name: unifrac-nrp-script
      - name: unifrac-nrp-script2
        configMap:
          items:
          - key: run_300k_support.sh
            path: run_300k_support.sh
          name: unifrac-nrp-script
